logging:
  level:
    ROOT: INFO
    ai.flowx.quickstart.connector: INFO
    io.netty: INFO
    reactor.netty: INFO
    jdk.event.security: INFO

server:
  port: 8080

spring:
  application:
    name: currency exchange
  jackson:
    serialization:
      write_dates_as_timestamps: false
      fail-on-empty-beans: false

application:
  jaeger:
    enabled: true
    prefix: exchange

management:
  health:
    kafka.enabled: true

exchangerate-api:
  key: YOUR_API_KEY # get your free api key here https://www.exchangerate-api.com/docs/pair-conversion-requests
  scheme: https
  host: v6.exchangerate-api.com
  path: v6/{apiKey}/pair/{fromCurrency}/{toCurrency}/{amount}

spring.config.import: application-management.yml, application-kafka.yml
---
spring.config.activate.on-profile: dev

logging.level.ROOT: DEBUG
logging.level.ai.flowx.quickstart.connector: DEBUG