logging:
  level:
    ROOT: INFO
    ai.flowx.quickstart.connector: INFO
    io.netty: INFO
    reactor.netty: INFO
    jdk.event.security: INFO

server:
  port: 8080

spring:
  application:
    name: quickstart-connector # TODO 1. choose a meaningful name for your connector service
  jackson:
    serialization:
      write_dates_as_timestamps: false
      fail-on-empty-beans: false

application:
  jaeger:  # TODO optional: decide whether you want to use jaeger tracing in your setup and choose a prefix name
    enabled: false
    prefix: connector

management: # TODO optional: enable health check for all the services you use in case you add any
  health:
    kafka.enabled: true
    # db.enabled: true
    # mongo.enabled: true
    # redis.enabled: true
    # elasticsearch.enabled: true

spring.config.import: application-management.yml, application-kafka.yml
---
spring.config.activate.on-profile: dev

logging.level.ROOT: DEBUG
logging.level.ai.flowx.quickstart.connector: DEBUG