management:
  server:
    address: 0.0.0.0
    port: 8081
    base-path: /manage
  security:
    enabled: false
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "health,info,metrics,metric,prometheus"
    health.sensitive: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    caches:
      enabled: true
      cache:
        time-to-live: 10ms
  metrics:
    export:
      prometheus:
        enabled: false
    tags:
      application: ${spring.application.name}
  health:
    defaults.enabled: true