management:
  server:
    address: 0.0.0.0
    port: 8081
    base-path: /manage
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "health,info,metrics,prometheus,logger"
    health.sensitive: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    caches:
      enabled: true
      cache:
        time-to-live: 10ms
  prometheus:
    metrics:
      export:
        enabled: true
    tags:
      application: ${spring.application.name}
  health:
    defaults.enabled: true